### ISSUE TITLE
cargo test-sbf not working for template program(counter)

### ISSUE THREAD

**Issue by Perelyn-sama** [regolith-labs/steel#15]
I ran `steel new demo` and `cargo build-sbf` and everything worked fine but when I tried to run `cargo test-sbf` I get these errors:

![Screenshot 2024-10-19 at 2 31 01 PM](https://github.com/user-attachments/assets/3ba06a14-5dfa-444b-870a-d92d516038e1)

**Comment by thearyanag** [comment]
hey, not sure why it's throwing that, can you please include these scripts in a package.json and run from them, these are recommended settings by https://github.com/solana-developers/program-examples 

```
"scripts": {
      "test": "pnpm ts-mocha -p ./tsconfig.json -t 1000000 ./tests/test.ts",
      "build-and-test": "cargo build-sbf --manifest-path=./program/Cargo.toml --sbf-out-dir=./tests/fixtures && pnpm test",
      "build": "cargo build-sbf --manifest-path=./program/Cargo.toml --sbf-out-dir=./program/target/so",
      "deploy": "solana program deploy ./program/target/so/counter_program.so"
    }
```
    
and tsconfig.json can look like this,
    
```
    {
    "compilerOptions": {
      "types": ["mocha", "chai", "node"],
      "typeRoots": ["./node_modules/@types"],
      "lib": ["es2015"],
      "module": "commonjs",
      "target": "es6",
      "esModuleInterop": true
    }
  }
  ```
  
  and example working program is also here, https://github.com/thearyanag/solana-program-examples/tree/main/basics/counter/steel

**Comment by Perelyn-sama** [comment]
I got the same error when I ran your version :/

**Comment by Perelyn-sama** [comment]
@HardhatChad please help :/

**Comment by Perelyn-sama** [comment]
found a solution, use `base64` insteaed of `bs64`

```
program/cargo.toml 

# bs64 = "0.1.2"
base64 = "0.21"
```

**Comment by Perelyn-sama** [comment]
Also, this might be just an m1 issue. 

@thearyanag I'm assuming you're not on an m1, right? Since the tests work for you

**Comment by Perelyn-sama** [comment]
> Did this resolve the issue?
yes, it did
