### ISSUE TITLE
how can I use `msg!()` in steel? 

### ISSUE THREAD

**Issue by Perelyn-sama** [regolith-labs/steel#16]
When I import `use solana_sdk::msg;` in my instruction and run `cargo build-sbf`, I get this error:

![Screenshot 2024-10-19 at 4 26 14 PM](https://github.com/user-attachments/assets/cf8f9507-174d-4cd6-bc50-dbb1e22c28f0)

Can I use `msg!` in steel or is there another way for logs?
If there currently isn't a way to log stuff, I'd like to help with the implementation :)

**Comment by Perelyn-sama** [comment]
code can be found here - https://github.com/Perelyn-sama/program-examples/blob/steel/hello-solana/basics/hello-solana/steel/program/src/hello.rs

**Comment by thearyanag** [comment]
you can use ```use solana_program::msg;``` , which will work

**Comment by Perelyn-sama** [comment]
It worked, thank you :) 

can you check this one out too - https://github.com/regolith-labs/steel/issues/15
