### ISSUE TITLE
can't build new steel project while using v2

### ISSUE THREAD

**Issue by Perelyn-sama** [regolith-labs/steel#18]
:/

![Screenshot 2024-10-23 at 10 00 48 PM](https://github.com/user-attachments/assets/da1a8b23-d11f-405d-9da9-de65e2352632)

**Comment by Perelyn-sama** [comment]
remove `repository.workspace = true` in `api/cargo.toml` and `program/cargo.toml` and it compiles

**Comment by adpthegreat** [comment]
Check out  #21
