### ISSUE TITLE
using rent in test file 

### ISSUE THREAD

**Issue by Perelyn-sama** [regolith-labs/steel#20]
When I try to use `Rent::get().unwrap().minimum_balance(0)` in my test file, it causes this error: 

```
failures:

---- run_test stdout ----
thread 'run_test' panicked at /Users/mac/.cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-program-test-1.18.26/src/lib.rs:99:17:
Invoke context not set!
```

I import `Rent` with `use solana_program::rent::Rent;` 

Am I doing something wrong? : /

**Comment by HardhatChad** [comment]
Pretty sure `Rent::get()` only works in the runtime. It fetches the rent sysvar account
